### ISSUE TITLE
Sample Code

### ISSUE THREAD

**Issue by GaryGriggs** [IvanAntipov/Ufal.UDPipe.CSharp.Unofficial#1]
I'm really excited to see NuGet package as I am processing text in lots of languages.  Will you post sample code that demonstrates how to tokenize and parse a sentence?

**Comment by IvanAntipov** [comment]
@GaryGriggs I added F# usage example, C# example will be added soon

**Comment by IvanAntipov** [comment]
@GaryGriggs for C# see https://github.com/IvanAntipov/Ufal.UDPipe.CSharp.Unofficial/tree/master/Examples/CSharp

**Comment by GaryGriggs** [comment]
@IvanAntipov The code is running with superior results.  Thank you for the examples and for publishing this package.
